// Generated by CoffeeScript 1.7.1
(function() {
  Handlebars.registerHelper('makeFullURI', function(uri) {
    if (uri === null) {
      return '';
    } else if (uri.substr(0, 4) === 'http') {
      return uri;
    } else {
      return "http://" + uri;
    }
  });

  $(function() {
    var $project_listing, project_handlebars, project_template, projects, spreadsheet_url;
    spreadsheet_url = 'https://app.flatsheet.io/api/v1/sheets/fltgr1f77g5tjmqnhcoviq';
    projects = [];
    $project_listing = $('#project-listing');
    project_handlebars = $('#project-template').html();
    project_template = Handlebars.compile(project_handlebars);
    return $.getJSON(spreadsheet_url, function(data) {
      var $row, i, project, projects_slice, slice_size, _i, _j, _len, _ref, _results;
      projects = data.rows;
      slice_size = 3;
      _results = [];
      for (i = _i = 0, _ref = projects.length; slice_size > 0 ? _i < _ref : _i > _ref; i = _i += slice_size) {
        projects_slice = projects.slice(i, i + slice_size);
        $row = $('<div class="row"></div>');
        for (_j = 0, _len = projects_slice.length; _j < _len; _j++) {
          project = projects_slice[_j];
          $row.append(project_template(project));
        }
        _results.push($project_listing.append($row));
      }
      return _results;
    });
  });

}).call(this);
